name: diplom
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bot_toast: ^4.0.1
  cached_network_image: ^3.1.0+1
  cupertino_icons: ^1.0.4
  date_range_form_field: ^1.0.2
  dio: ^4.0.1
  effective_dart: ^1.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.2
  flutter_html: ^2.1.5
  flutter_linkify: ^5.0.2
  flutter_lints: ^1.0.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.23.0+1
  geocoding: ^2.0.2
  intl: ^0.17.0
  provider: ^6.0.1
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.8
  syncfusion_flutter_charts: ^19.3.53
  syncfusion_flutter_maps: ^19.4.47-beta
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
