name: diplom
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bot_toast: ^4.0.1
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.1
  effective_dart: ^1.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.23.0+1
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
